version: 2
updates:

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "nicce"
    commit-message:
      prefix: "build(deps): "

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "nicce"
    commit-message:
      prefix: "build(deps): "
