---
run:
  timeout: 5m
  skip-dirs:
    - bin
    - generated
linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - goheader
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wrapcheck
    - wsl
issues:
  exclude-use-default: false
  max-same-issues: 0
  exclude-rules:
    - path: _test.go
      linters:
        - dupl
        - errorlint
        - gocyclo
        - goerr113
linters-settings:
  dupl:
    threshold: 200
  exhaustive:
    default-signifies-exhaustive: true
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: exported
        disabled: false
  wrapcheck:
    ignorePackageGlobs:
      - encoding/*
      - github.com/gofiber/fiber/*
      - google.golang.org/grpc/status
