on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

name: on-merge-to-main

jobs:
  Verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
    secrets: inherit
  Tag:
    name: Tag
    uses: ./.github/workflows/tag.yml
    needs: Verify
    secrets: inherit